name: Publish Create Onchain Agent to PyPI

on:
  workflow_dispatch:

jobs:
  deploy-pypi-create-onchain-agent:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python/create-onchain-agent
    environment:
      name: pypi
      url: https://pypi.org/p/create-onchain-agent
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --only main

      - name: Build package
        id: build
        run: |
          poetry build
          echo "version=$(poetry version --short)" >> $GITHUB_OUTPUT

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/create-onchain-agent/dist/

      - name: Tag package
        run: |
          TAG="create-onchain-agent@${{ steps.build.outputs.version }}"
          MESSAGE="Release create-onchain-agent version ${{ steps.build.outputs.version }}"
          git tag -a $TAG -m "$MESSAGE"
          git push origin $TAG
