name: Publish Docs to Github Pages

on:
  workflow_dispatch:

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 10

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: ./typescript

      - name: Install and Build JSDocs
        working-directory: ./typescript
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
          pnpm run docs

      - name: Build AgentKit JSDocs
        run: |
          mkdir -p docs/agentkit/typescript
          cp -r typescript/agentkit/docs/* docs/agentkit/typescript

      - name: Build AgentKit LangChain JSDocs
        run: |
          mkdir -p docs/agentkit-langchain/typescript
          cp -r typescript/framework-extensions/langchain/docs/* docs/agentkit-langchain/typescript

      - name: Build AgentKit Vercel AI SDK JSDocs
        run: |
          mkdir -p docs/agentkit-vercel-ai-sdk/typescript
          cp -r typescript/framework-extensions/vercel-ai-sdk/docs/* docs/agentkit-vercel-ai-sdk/typescript

      - name: Build AgentKit Model Context Protocol JSDocs
        run: |
          mkdir -p docs/agentkit-model-context-protocol/typescript
          cp -r typescript/framework-extensions/model-context-protocol/docs/* docs/agentkit-model-context-protocol/typescript

      - name: Set up Python 3.10
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies for Coinbase AgentKit Python
        run: |
          cd python/coinbase-agentkit
          uv sync --all-extras --dev
          cd ..

      - name: Build Sphinx Documentation for Coinbase AgentKit Python
        run: |
          cd python/coinbase-agentkit
          make docs
          cd docs
          make html
          cd ../../..
          mkdir -p docs/coinbase-agentkit/python
          cp -r python/coinbase-agentkit/docs/_build/html/* docs/coinbase-agentkit/python

      - name: Install dependencies for Coinbase AgentKit LangChain Python
        run: |
          cd python/framework-extensions/langchain
          uv sync --all-extras --dev
          cd ../..

      - name: Build Sphinx Documentation for Coinbase AgentKit LangChain Python
        run: |
          cd python/framework-extensions/langchain
          make docs
          cd docs
          make html
          cd ../../../..
          mkdir -p docs/coinbase-agentkit-langchain/python
          cp -r python/framework-extensions/langchain/docs/_build/html/* docs/coinbase-agentkit-langchain/python

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: false
